version: '3.8'
services:
  db:
    container_name: 'db'
    image: 'postgres:11.5-alpine'
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=recipe,testdb
  redis:
    container_name: 'redis'
    image: 'redis'

  server:
    container_name: 'server'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3005:3005'
    env_file: .env
    depends_on:
      - db
      - redis
    command: npm run local
    working_dir: /app
    volumes:
      - ./:/app:cached
