version: '3.8'
services:
  ### Databases ###
  ravendb:
    container_name: 'ravendb'
    image: 'ravendb/ravendb'
    hostname: 'ravendb'
    ports:
      - '8080:8080'
      - '38888:38888'
    # environment:
    #   RAVEN_ARGS: --ServerUrl=http://0.0.0.0:8080 --Setup.Mode=None --Security.UnsecuredAccessAllowed=PublicNetwork --License.Eula.Accepted=true
    volumes:
      - .tmp/:/opt/RavenDB/Server/RavenData
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_ServerUrl=http://0.0.0.0:8080
      - RAVEN_License.Eula.Accepted=true

  redis:
    container_name: 'queue'
    image: 'redis'

  ### Server ###
  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3005:3005'
    env_file: .env
    depends_on:
      - ravendb
      - redis
    command: npm run testing
    working_dir: /app
    volumes:
      - ./:/app:cached
